/**
 * About content.
 *
 * Copy and team are taken from the developer's own corporate site,
 * spheredevelopments.ca (About Us, Our Experience, Our Principles, Our Team),
 * at the client's direction — Stax is a Sphere Developments project.
 *
 * Edited for context, not invented: the source is written for an investor and
 * homebuyer audience across every asset class Sphere builds. Here it is
 * trimmed to the parts that answer a student renter's actual question, which
 * is "who is my landlord going to be." The claims themselves are unchanged.
 *
 * Nothing in this file is placeholder text any more, with two exceptions,
 * both flagged inline: the headline statistics and Vruti Shah's headshot.
 */

export const DEVELOPER = {
  name: "Sphere Developments",
  url: "https://spheredevelopments.ca",
  headOffice: "170 Robert Speck Parkway, Unit 203, Mississauga, ON L4Z 3G1",
  email: "contact@spheredevelopments.ca",
} as const;

export const ABOUT_STORY = {
  eyebrow: "The developer",
  heading: "A different kind of home, in a neighbourhood planned around connection.",
  paragraphs: [
    "Stax is a Sphere Developments community. Founded by a group of industry leaders with a 360-degree vision for the future, Sphere is a world away from the usual development company — a boutique focus on finding and developing properties of unique and enduring appeal, and a full circle approach to home building.",
    "From curating the land acquisition, to inspired community planning, to artful architectural design, and most importantly a rewarding experience for the people who live there, Sphere brings a personal hands-on commitment to every step of the process.",
    "The result is a different kind of home, in a neighbourhood where community and connection are planned into every detail.",
  ],
};

export const ABOUT_EXPERIENCE = {
  eyebrow: "Our experience",
  heading: "Our vision is driven by our experience.",
  body: "The leadership team at Sphere Developments has decades of combined experience in the financing, development and sales of real estate projects. From custom homes to high-rise towers, a deep understanding of the development timeline has allowed the team to achieve tremendous success across a wide range of projects.",
  /**
   * Purpose-built rental and stacked townhomes lead the list because that is
   * exactly what Stax is — this is the part of the track record that is
   * directly relevant rather than merely impressive.
   */
  assetClasses: [
    "Purpose-built rental communities",
    "Stacked townhomes",
    "Condominium towers",
    "Single-family homes",
    "Commercial office and retail",
  ],
  closing:
    "Sphere has successfully led the creation of purpose-built rental communities designed to meet long-term housing demand — communities that prioritise livability, efficiency and professional property management, in highly connected, amenity-rich neighbourhoods.",
};

/**
 * TODO(client): Sphere's corporate site publishes these four figures but the
 * counters are unfilled — every one renders as "$0M" or "0". No real numbers
 * exist to carry over, so the stat row is omitted from the page rather than
 * shown with zeros or with figures we made up. Supply the values and
 * uncomment the block in app/about/page.tsx.
 */
export const ABOUT_STATS: { value: string; label: string }[] = [];

/** From Our Principles. The four that a renter can actually feel. */
export const ABOUT_PRINCIPLES = [
  {
    title: "Accountability",
    body: "We hold our team and each person we work with accountable for their performance, and assist them in their process to ensure the success of every project.",
  },
  {
    title: "Transparency",
    body: "We maintain an open dialogue between our teams and our stakeholders. Our open-door policy encourages communication on every project we work on.",
  },
  {
    title: "Detail oriented",
    body: "We understand the importance of the little details, and comb over our work to ensure every base has been covered before moving to the next step.",
  },
  {
    title: "Customer care",
    body: "Sphere prides itself on being a builder that is accountable and honourable. All customer care issues are addressed promptly.",
  },
];

export type TeamMember = {
  name: string;
  role: string;
  /** Slug in public/team, generated by scripts/process-images.mjs. */
  photo?: string;
  bio?: string;
};

/**
 * Real people, real names, real headshots — pulled from Sphere's own team page.
 *
 * Deliberately no bios: the corporate site publishes names and titles only, so
 * writing a paragraph for each of these people would mean inventing a career
 * history for a named individual. The `bio` field is here for when the client
 * supplies real ones.
 *
 * TODO(client): Vruti Shah's headshot is a "coming soon" placeholder on the
 * Sphere site, so the card renders the brand mark. Supply the photo and drop
 * it into ../Team/vruti-shah.jpg, then re-run `npm run images`.
 */
export const ABOUT_TEAM: TeamMember[] = [
  { name: "Rohan Gawri", role: "President", photo: "rohan-gawri" },
  { name: "AJ Uppal", role: "Executive Vice President", photo: "aj-uppal" },
  { name: "Vruti Shah", role: "Development Manager" },
  { name: "Katie Shah", role: "Vice President, Sales and Marketing", photo: "katie-shah" },
  { name: "Jeffrey Leung", role: "Controller", photo: "jeffrey-leung" },
  { name: "John Santos", role: "Administrative Assistant", photo: "john-santos" },
];

/**
 * TODO(client): confirm the first two dates. Everything from "Registration
 * opens" onward is derived from the published September 2027 occupancy.
 */
export const ABOUT_TIMELINE = [
  {
    date: "2024",
    title: "Site plan approval",
    body: "Approval secured through creative collaboration with the City of St. Catharines, expanding the plan from 223 units to 248.",
    state: "done" as const,
  },
  {
    date: "2026",
    title: "Construction underway",
    body: "Eight residential blocks with commercial units integrated at grade.",
    state: "done" as const,
  },
  {
    date: "Now",
    title: "Registration opens",
    body: "The interest list opens. Floor plans, pricing and lease dates are released to it first.",
    state: "current" as const,
  },
  {
    date: "Spring 2027",
    title: "Pricing released",
    body: "Rents, lease terms and the full plan pack published to the registration list ahead of public listing.",
    state: "upcoming" as const,
  },
  {
    date: "Summer 2027",
    title: "Leasing opens",
    body: "Suites released for signing, registration list first.",
    state: "upcoming" as const,
  },
  {
    date: "September 2027",
    title: "Move-in",
    body: "First residents take occupancy for the 2027–28 academic year.",
    state: "upcoming" as const,
  },
];
