/**
 * About content.
 *
 * Copy and team are taken from the developer's own corporate site,
 * spheredevelopments.ca (About Us, Our Experience, Our Principles, Our Team),
 * at the client's direction — Stax is a Sphere Developments project.
 *
 * Edited for context, not invented: the source is written for an investor and
 * homebuyer audience across every asset class Sphere builds. Here it is
 * trimmed to the parts that answer a student renter's actual question, which
 * is "who is my landlord going to be." The claims themselves are unchanged.
 *
 * Nothing in this file is placeholder text any more, with one exception,
 * flagged inline: the headline statistics.
 */

export const DEVELOPER = {
  name: "Sphere Developments",
  url: "https://spheredevelopments.ca",
  headOffice: "170 Robert Speck Parkway, Unit 203, Mississauga, ON L4Z 3G1",
  email: "contact@spheredevelopments.ca",
} as const;

export const ABOUT_STORY = {
  eyebrow: "The developer",
  heading: "A different kind of home, in a neighbourhood planned around connection.",
  paragraphs: [
    "Stax is a Sphere Developments community. Founded by a group of industry leaders with a 360-degree vision for the future, Sphere is a world away from the usual development company — a boutique focus on finding and developing properties of unique and enduring appeal, and a full circle approach to home building.",
    "From curating the land acquisition, to inspired community planning, to artful architectural design, and most importantly a rewarding experience for the people who live there, Sphere brings a personal hands-on commitment to every step of the process.",
    "The result is a different kind of home, in a neighbourhood where community and connection are planned into every detail.",
  ],
};

export const ABOUT_EXPERIENCE = {
  eyebrow: "Our experience",
  heading: "Our vision is driven by our experience.",
  body: "The leadership team at Sphere Developments has decades of combined experience in the financing, development and sales of real estate projects. From custom homes to high-rise towers, a deep understanding of the development timeline has allowed the team to achieve tremendous success across a wide range of projects.",
  /**
   * Purpose-built rental and stacked townhomes lead the list because that is
   * exactly what Stax is — this is the part of the track record that is
   * directly relevant rather than merely impressive.
   */
  assetClasses: [
    "Purpose-built rental communities",
    "Stacked townhomes",
    "Condominium towers",
    "Single-family homes",
    "Commercial office and retail",
  ],
  closing:
    "Sphere has successfully led the creation of purpose-built rental communities designed to meet long-term housing demand — communities that prioritise livability, efficiency and professional property management, in highly connected, amenity-rich neighbourhoods.",
};

/**
 * TODO(client): Sphere's corporate site publishes these four figures but the
 * counters are unfilled — every one renders as "$0M" or "0". No real numbers
 * exist to carry over, so the stat row is omitted from the page rather than
 * shown with zeros or with figures we made up. Supply the values and
 * uncomment the block in app/about/page.tsx.
 */
export const ABOUT_STATS: { value: string; label: string }[] = [];

/** From Our Principles. The four that a renter can actually feel. */
export const ABOUT_PRINCIPLES = [
  {
    title: "Accountability",
    body: "We hold our team and each person we work with accountable for their performance, and assist them in their process to ensure the success of every project.",
  },
  {
    title: "Transparency",
    body: "We maintain an open dialogue between our teams and our stakeholders. Our open-door policy encourages communication on every project we work on.",
  },
  {
    title: "Detail oriented",
    body: "We understand the importance of the little details, and comb over our work to ensure every base has been covered before moving to the next step.",
  },
  {
    title: "Customer care",
    body: "Sphere prides itself on being a builder that is accountable and honourable. All customer care issues are addressed promptly.",
  },
];

export type TeamMember = {
  name: string;
  role: string;
  /** Slug in public/team, generated by scripts/process-images.mjs. */
  photo?: string;
  bio?: string;
};

/**
 * Real people, real names, real headshots — pulled from Sphere's own team page.
 *
 * Deliberately no bios: the corporate site publishes names and titles only, so
 * writing a paragraph for each of these people would mean inventing a career
 * history for a named individual. The `bio` field is here for when the client
 * supplies real ones.
 *
 * FOUR, at the client's direction (Pass 6 §4.1). Vruti Shah (Development
 * Manager) and John Santos (Administrative Assistant) come off the page.
 *
 * Two consequences, both handled in app/about/page.tsx. The grid drops to
 * 2x2 — at three columns four people leave a lone card and two gaps on the
 * second row, and an unbalanced row on a "who you'll deal with" page reads as
 * somebody having left. And the broken-portrait bug goes with the card that
 * caused it: Vruti Shah's headshot was a "coming soon" placeholder on the
 * Sphere site, so hers was the one card rendering the brand mark instead of a
 * face.
 *
 * Every remaining member has a real photo, so the `StaxMark` fallback in
 * `TeamCard` no longer fires for anyone. It stays, because the next person
 * added will arrive before their headshot does.
 */
export const ABOUT_TEAM: TeamMember[] = [
  { name: "Rohan Gawri", role: "President", photo: "rohan-gawri" },
  { name: "AJ Uppal", role: "Executive Vice President", photo: "aj-uppal" },
  { name: "Katie Shah", role: "Vice President, Sales and Marketing", photo: "katie-shah" },
  { name: "Jeffrey Leung", role: "Controller", photo: "jeffrey-leung" },
];

/**
 * Where things stand. ORDERED BY DATE, and that ordering is the change
 * (Pass 6 §4.2).
 *
 * The client's dates put pricing (Sept 2026) BEFORE the interest list opens
 * (Fall 2026), which swaps steps 3 and 4 against what the site used to show.
 * It reads perfectly well in that order — publish the rents, open the list,
 * then lease — but it does move one promise: the registration step can no
 * longer claim pricing is released to the list first, because pricing is
 * already public by the time the list exists. The same edit is made to the
 * Register section's body copy and to the rent FAQ.
 *
 * `state: "current"` is on Construction underway, not on Registration. The
 * client has said explicitly not to claim registration is open, and August
 * 2026 is not Fall 2026 — construction is what is actually happening now.
 * That flag drives both the NOW badge and the StaxMark bullet, so moving it
 * moves the "you are here" marker with it.
 */
export const ABOUT_TIMELINE = [
  {
    date: "2024",
    title: "Site plan approval",
    body: "Approval secured through creative collaboration with the City of St. Catharines, expanding the plan from 223 units to 248.",
    state: "done" as const,
  },
  {
    date: "2026",
    title: "Construction underway",
    body: "Ten residential blocks with commercial units integrated at grade.",
    state: "current" as const,
  },
  {
    date: "Sept 2026",
    title: "Pricing released",
    body: "Rents and lease terms published.",
    state: "upcoming" as const,
  },
  {
    date: "Fall 2026",
    title: "Registration opens",
    body: "The interest list opens. Floor plans and lease dates are released to it first.",
    state: "upcoming" as const,
  },
  {
    date: "Jan 2027",
    title: "Leasing opens",
    body: "Suites released for signing, registration list first.",
    state: "upcoming" as const,
  },
  {
    date: "September 2027",
    title: "Move-in",
    body: "First residents take occupancy for the 2027–28 academic year.",
    state: "upcoming" as const,
  },
];
